# Generated by Django 5.2.4 on 2025-07-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_timesheetentry_created_at_timesheetentry_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timesheetentry",
            options={
                "verbose_name": "Time Sheet Entry",
                "verbose_name_plural": "Time Sheet Entries",
            },
        ),
    ]
