# Generated by Django 5.2.4 on 2025-07-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_timesheetentry_options"),
        ("core", "0004_create_default_users"),
    ]

    operations = []
